services:
  meilisearch:
    image: getmeili/meilisearch:v1.8
    restart: always
    ports:
      - ${MEILISEARCH_PORT}:7700
    volumes:
      - ./data/meilisearch:/meili_data
  typesense:
    image: typesense/typesense:26.0
    restart: always
    ports:
      - ${TYPESENSE_PORT}:8108
    volumes:
      - ./data/typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
  postgres:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass secret
    volumes:
      - ./data/redis:/data
